### PR TITLE
Fix color implementation of schemaTable

### LINKED ISSUE #74: Fix color implementation of schemaTable
see https://github.com/taskcluster/material-ui-json-schema-viewer/pull/72#discussion_r378130930

### PR DESCRIPTION
**Pull request by JiwoonKim**
Closes #74 

**Applied Changes**
- [x] fix color of code class style (used for 'type' keyword)
- [x] fix color of comment class style (used for combination types)
- [x] fix color of table grid borders
- [x] fix color of expand/shrink buttons

**Screenshot Results**

| type block | expand/shrink button | 
|:---:|:---:|
| image | image | 
| __comments__ | __grid borders__ |
| image | image |

### CODE REVIEW

File: src/components/SchemaTable/index.jsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ const useStyles = makeStyles(theme => ({
   },
   /** Rows for the left and right panels */
   row: {
-    borderBottom: `${theme.spacing(0.25)}px solid ${theme.palette.divider}`,
+    borderBottom: `${theme.spacing(0.25)}px solid ${theme.palette.grey[300]}`,
```
Comment (JiwoonKim) [inline src/components/SchemaTable/index.jsx]: Replaced grid border colors to `theme.palette.grey` instead of `theme.palette.divider` since the theme's divider is not automated according to the color given by the user. 
Using a grey color will ensure that the grid borders are always visible since the background color of the table is always either a white or black (specifically, either #fff or rgba(0,0,0,0.87)) due to using `theme.palette.getContrastText()`.

File: src/components/SchemaTable/index.jsx [hunk 2]
```diff
@@ -50,12 +50,13 @@ const useStyles = makeStyles(theme => ({
...
   code: {
-    backgroundColor: theme.palette.grey[300],
+    backgroundColor: theme.palette.text.primary,
+    color: theme.palette.getContrastText(theme.palette.text.primary),
     padding: `0 ${theme.spacing(0.5)}px`,
   },
   /** Comments within the left panel (used for combination types) */
   comment: {
-    color: theme.palette.text.hint,
+    color: theme.palette.text.primary,
```
Comment (helfi92) [inline src/components/SchemaTable/index.jsx]: What was the reason for changing `hint` to `primary`?

File: src/components/SchemaTable/index.jsx (hunk 1 above)
Comment (helfi92) [reply src/components/SchemaTable/index.jsx]: > since the theme's divider is not automated according to the color given by the user.

I'm not sure I understand. Any clarifications would be appreciated.

File: src/components/SchemaTable/index.jsx (hunk 2 above)
Comment (JiwoonKim) [reply src/components/SchemaTable/index.jsx]: Using `hint`, the comments are not visible against a dark background. So the change result would be

| before | after |
|:---:|:---:|
|  |  |

Alternatively, we could leave comment color configuration to the user, so that it is the user's responsibility to configure the theme colors so that the comments are visible. Would this be better than to use `primary` ?

Comment (helfi92) [reply src/components/SchemaTable/index.jsx]: If we just use the default dark theme with

```jsx
   const colorfulTheme = createMuiTheme({
    palette: {
      type: 'dark'
    },
  });
```

then the comment will be readable:

Screen Shot 2020-02-14 at 3 15 10 PM

If the user decides to change the default dark theme to something else like

```jsx
  const colorfulTheme = createMuiTheme({
    palette: {
      text: {
        primary: '#ffc107',
      },
    },
  });
```

then they would also have to change other theme values to make it sit nicely. Here's a quick example that's incomplete. Let me know what you think.

```diff
diff --git a/src/components/Header/index.jsx b/src/components/Header/index.jsx
index e4b7b72..408eeb6 100644
--- a/src/components/Header/index.jsx
+++ b/src/components/Header/index.jsx
@@ -7,7 +7,7 @@ import { schema } from '../../utils/prop-types';
 
 const useStyles = makeStyles(theme => ({
   container: {
-    backgroundColor: theme.palette.getContrastText(theme.palette.text.primary),
+    backgroundColor: theme.palette.background.paper,
     color: theme.palette.text.primary,
     padding: `${theme.spacing(1.5)}px ${theme.spacing(1)}px`,
     marginBottom: theme.spacing(1),
diff --git a/src/components/SchemaTable/index.jsx b/src/components/SchemaTable/index.jsx
index ec6ab9d..4b18ae9 100644
--- a/src/components/SchemaTable/index.jsx
+++ b/src/components/SchemaTable/index.jsx
@@ -16,13 +16,13 @@ const useStyles = makeStyles(theme => ({
   },
   /** The left panel of the Schema Table */
   leftPanel: {
-    backgroundColor: theme.palette.getContrastText(theme.palette.text.primary),
+    backgroundColor: theme.palette.background.paper,
     borderRight: `${theme.spacing(1)}px solid ${theme.palette.divider}`,
     overflowX: 'auto',
   },
   /** The right panel of the Schema Table */
   rightPanel: {
-    backgroundColor: theme.palette.getContrastText(theme.palette.text.primary),
+    backgroundColor: theme.palette.background.paper,
     overflowX: 'auto',
   },
   /** Rows for the left and right panels */
@@ -53,7 +53,7 @@ const useStyles = makeStyles(theme => ({
    * in the left panel of the schema table component.
    */
   code: {
-    backgroundColor: theme.palette.grey[300],
+    backgroundColor: theme.palette.getContrastText(theme.palette.text.primary),
     padding: `0 ${theme.spacing(0.5)}px`,
   },
   /** Comments within the left panel (used for combination types) */
@@ -73,7 +73,7 @@ const useStyles = makeStyles(theme => ({
    */
   chip: {
     color: theme.palette.text.primary,
-    borderColor: theme.palette.text.primary
+    borderColor: theme.palette.text.secondary,
   },
 }));
 
diff --git a/src/components/SchemaViewer/index.stories.js b/src/components/SchemaViewer/index.stories.js
index fce1803..9e82e3e 100644
--- a/src/components/SchemaViewer/index.stories.js
+++ b/src/components/SchemaViewer/index.stories.js
@@ -138,9 +138,15 @@ export const customThemes = () => {
   });
   const colorfulTheme = createMuiTheme({
     palette: {
+      background: {
+        paper: '#000',
+      },
       text: {
         primary: '#ffc107',
+        secondary: '#ffc53d',
+        hint: '#ddd',
       },
+      divider: '#4f4f4f',
     },
   });
 
diff --git a/src/components/SourceView/index.jsx b/src/components/SourceView/index.jsx
index 7ce2997..a4885f8 100644
--- a/src/components/SourceView/index.jsx
+++ b/src/components/SourceView/index.jsx
@@ -4,7 +4,7 @@ import { schema } from '../../utils/prop-types';
 
 const useStyles = makeStyles(theme => ({
   view: {
-    backgroundColor: theme.palette.background.default,
+    backgroundColor: theme.palette.background.paper,
     color: theme.palette.text.primary,
     overflowX: 'auto',
   },
```

Dark theme:
Screen Shot 2020-02-14 at 3 55 51 PM

Colorful theme:
Screen Shot 2020-02-14 at 3 56 06 PM

Comment (JiwoonKim) [reply src/components/SchemaTable/index.jsx]: Sounds great! 👍 Applied changes!

File: src/components/SchemaTable/index.jsx (hunk 1 above)
Comment (JiwoonKim) [reply src/components/SchemaTable/index.jsx]: Reversing back to using `theme.palette.divider` and letting the user config the border colors instead. See https://github.com/taskcluster/material-ui-json-schema-viewer/pull/75/files#r379640957
