### PR TITLE
Fix vertical alignment of description column in right panel

### LINKED ISSUE #43: Fix vertical alignment of description column in right panel
**Describe the Bug**
the description column  does not vertically align between different rows and lines in the right panel

image

**To Reproduce**
check display of styleguide's Complex Nested Type

### PR DESCRIPTION
**Pull request by JiwoonKim**
Closes #43 
fix description keyword display in right panel

**Applied Changes**
- [x] remove description column from right panel
- [x] use  material-ui chips for keywords (other than description) and display on a single line
- [x] create a blank line between keywords line and description line

**Results**

- overall look of display in right panel

image

- tooltips are also displayed in chips on single line

### CODE REVIEW

File: src/utils/constants.js [hunk 1]
```diff
@@ -20,3 +21,10 @@ export const SKIP_KEYWORDS = [
   'oneOf',
   'not',
 ];
+
+/**
+ * Keywords used in schema that are descriptors.
+ * These are typically displayed in the rows of the right panel,
+ * separated by a blank line from the displayed chips.
+ */
+export const DESCRIPTOR_KEYWORDS = ['description', 'title'];
```
Comment (JiwoonKim) [inline src/utils/constants.js]: Included the `title` keyword to be separated along with the `description` keyword since it seemed better UI to only display keywords related to specifications in chip form and leave descriptive keywords out in simple text.
So the current display is like:

image

I was also thinking of maybe removing the `title: ` and `description: ` literals to further clean up the UI as well. Maybe in a format of `(title) description` ?



What do you think about this idea?

**Comment by JiwoonKim** [comment]
Noticing that there is a UI bug where the line width of the rows in the right panel is short when there are a lot of chip keywords to display.

image

Will open a separate issue to fix this problem once this PR is officially merged 😄

File: src/utils/constants.js (hunk 1 above)
Comment (helfi92) [reply src/utils/constants.js]: > I was also thinking of maybe removing the `title:` and `description:` literals to further clean up the UI as well

Agreed.

>.  Maybe in a format of (title) description ?

You can definitely give that a try. Another idea that comes to mind is to perhaps put the title and description in their own line and then use a different font-weight (e.g., bold) for the title. Something like:

---
(chip-1) (chip-2) ...

<strong>title</strong>
description

File: src/components/NormalRightRow/index.jsx [hunk 2]
```diff
@@ -1,50 +1,81 @@
...
+    if (descriptors.length > 0) {
+      if (specs.length > 0) {
+        lines.push(<div key="separator-line" className={classes.line} />);
+      }
+
+      descriptors.forEach(keyword => lines.push(displayDescriptor(keyword)));
+    }
+
+    return lines;
+  }
```
Comment (helfi92) [inline src/components/NormalRightRow/index.jsx]: A couple of things I noticed:
1. When there are more than 3 chips, a user is required to scroll the right panel to see the full list of chips.
2. If a description is really long, it will be really hard to read it currently since it requires scrolling horizontally bit by bit.
3. Looking for a given keyword chip requires scanning the list of chips from left to right.

Possible solutions:
1. Render at most 3 chips per line.
2. Add three triple dots at the end of the line to inform users that the description is longer than that. Upon hover, we could show the description in a tooltip.
3. Sort the list of chips alphabetically to improve the experience when looking for a certain keyword.

^ is something we can definitely do in a follow-up as an enhancement to the current implementation.

Comment (JiwoonKim) [reply src/components/NormalRightRow/index.jsx]: Great idea! 👍 
Opened #51 to further implement these features!

File: src/utils/constants.js (hunk 1 above)
Comment (JiwoonKim) [reply src/utils/constants.js]: > You can definitely give that a try. Another idea that comes to mind is to perhaps put the title and description in their own line and then use a different font-weight (e.g., bold) for the title. Something like:

Implemented bold weight to titles!
