### PR TITLE
Fix missing type keyword in schema cases

### LINKED ISSUE #64: Fix missing type keyword in schema cases
**Describe the Bug**
- Some schemas seem to miss the `type` keyword
  - ex. `metadata-metaschema.json` which is in our demo and also a Taskcluster schema as well
  - see https://github.com/taskcluster/material-ui-json-schema-viewer/blob/master/schemas/demo/metadata-metaschema.json

This is problematic since the current schema viewer uses the `type` property to render the schemas according to its type. Thus, the above example does not render any properties of the object since it does not explicitly specify its `type`.

**To reproduce**
Currently the `metadata-metaschema.json` example is not included in Storybook's examples. 
Will be able to reproduce this problem once #63 is merged into the master branch. 
In the meantime, refer to the screenshot and schema file comparison example instead (shown below).

**Example**
- the problematic code within `metadata-metaschema.json`:
```js
"recurse": {
    "properties": {
     ...
    }
    // 'type' is not specified 
}
```
- screenshot of this part in `schemaViewer`: does not correctly render the properties even though they are specified since no `type` is given
image

### PR DESCRIPTION
**Pull request by JiwoonKim**
Closes #64 

**Applied Changes**
- if a type is not specified, display ⚠️ icon in the left row with tooltip to instruct user to refer to the source instead

**Screenshot Results**

image

### CODE REVIEW

File: src/components/NormalLeftRow/index.jsx [hunk 1]
```diff
@@ -50,6 +51,17 @@ function NormalLeftRow({ classes, treeNode, refType, setSchemaTree }) {
...
+    /**
+     * If type is not specified, create a tooltip with an icon.
+     */
+    if (!type) {
+      return (
+        <Tooltip title={TOOLTIP_DESCRIPTIONS.noType}>
+          <WarningIcon color="inherit" />
+        </Tooltip>
+      );
+    }
```
Comment (helfi92) [inline src/components/NormalLeftRow/index.jsx]: Adding an example in the storybook where we can see this show up could be good.

Comment (JiwoonKim) [reply src/components/NormalLeftRow/index.jsx]: Added example 👍
